// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiEwxUG6pP1fNvvvuEnI7hWmL9HI-85-8',
    appId: '1:396714087650:web:42faecfef8761b7d0a7abb',
    messagingSenderId: '396714087650',
    projectId: 'disabilapp',
    authDomain: 'disabilapp.firebaseapp.com',
    storageBucket: 'disabilapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6BTLEHpopFtgq2VSFJlIiZ6Q6hTrlDCo',
    appId: '1:396714087650:android:89b1c8bd74bb313f0a7abb',
    messagingSenderId: '396714087650',
    projectId: 'disabilapp',
    storageBucket: 'disabilapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9Wb0j0ryKtAgLSagpLCTL8_WHpewjkg',
    appId: '1:396714087650:ios:91c634b621c6fbb90a7abb',
    messagingSenderId: '396714087650',
    projectId: 'disabilapp',
    storageBucket: 'disabilapp.appspot.com',
    iosBundleId: 'it.giodefa96.disabilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK9Wb0j0ryKtAgLSagpLCTL8_WHpewjkg',
    appId: '1:396714087650:ios:91c634b621c6fbb90a7abb',
    messagingSenderId: '396714087650',
    projectId: 'disabilapp',
    storageBucket: 'disabilapp.appspot.com',
    iosBundleId: 'it.giodefa96.disabilapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiEwxUG6pP1fNvvvuEnI7hWmL9HI-85-8',
    appId: '1:396714087650:web:2a99992e1135f4ff0a7abb',
    messagingSenderId: '396714087650',
    projectId: 'disabilapp',
    authDomain: 'disabilapp.firebaseapp.com',
    storageBucket: 'disabilapp.appspot.com',
  );
}
